/* THIS FILE IS AUTO-GENERATED ! DO NOT MODIFY ! Date: 07/08/2023, 13:41:15 */
const CONSTS = require('../consts')
module.exports = {
  [CONSTS.ITEM_PROPERTY_ABILITY_BONUS]: require('./ability-bonus'),
  [CONSTS.ITEM_PROPERTY_AC_BONUS]: require('./ac-bonus'),
  [CONSTS.ITEM_PROPERTY_ADVANTAGE]: require('./advantage'),
  [CONSTS.ITEM_PROPERTY_ATTACK_BONUS]: require('./attack-bonus'),
  [CONSTS.ITEM_PROPERTY_AURA]: require('./aura'),
  [CONSTS.ITEM_PROPERTY_CONDITION_IMMUNITY]: require('./condition-immunity'),
  [CONSTS.ITEM_PROPERTY_CRITICAL_THREAT]: require('./critical-threat'),
  [CONSTS.ITEM_PROPERTY_DAMAGE_BONUS]: require('./damage-bonus'),
  [CONSTS.ITEM_PROPERTY_DAMAGE_IMMUNITY]: require('./damage-immunity'),
  [CONSTS.ITEM_PROPERTY_DAMAGE_REDUCTION]: require('./damage-reduction'),
  [CONSTS.ITEM_PROPERTY_DAMAGE_RESISTANCE]: require('./damage-resistance'),
  [CONSTS.ITEM_PROPERTY_DAMAGE_VULNERABILITY]: require('./damage-vulnerability'),
  [CONSTS.ITEM_PROPERTY_DISADVANTAGE]: require('./disadvantage'),
  [CONSTS.ITEM_PROPERTY_ENHANCEMENT]: require('./enhancement'),
  [CONSTS.ITEM_PROPERTY_EXTRA_ATTACKS]: require('./extra-attacks'),
  [CONSTS.ITEM_PROPERTY_EXTRA_WEIGHT]: require('./extra-weight'),
  [CONSTS.ITEM_PROPERTY_HP_BONUS]: require('./hp-bonus'),
  [CONSTS.ITEM_PROPERTY_MASSIVE_CRITICAL]: require('./massive-critical'),
  [CONSTS.ITEM_PROPERTY_MATERIAL_VULNERABILITY]: require('./material-vulnerability'),
  [CONSTS.ITEM_PROPERTY_MELEE_ATTACK_BONUS]: require('./melee-attack-bonus'),
  [CONSTS.ITEM_PROPERTY_MUMMY_ROT]: require('./mummy-rot'),
  [CONSTS.ITEM_PROPERTY_ON_DAMAGED]: require('./on-damaged'),
  [CONSTS.ITEM_PROPERTY_ON_HIT]: require('./on-hit'),
  [CONSTS.ITEM_PROPERTY_PHARMA]: require('./pharma'),
  [CONSTS.ITEM_PROPERTY_RANGED_ATTACK_BONUS]: require('./ranged-attack-bonus'),
  [CONSTS.ITEM_PROPERTY_REGEN]: require('./regen'),
  [CONSTS.ITEM_PROPERTY_REROLL]: require('./reroll'),
  [CONSTS.ITEM_PROPERTY_SAVING_THROW_BONUS]: require('./saving-throw-bonus'),
  [CONSTS.ITEM_PROPERTY_SKILL_BONUS]: require('./skill-bonus'),
  [CONSTS.ITEM_PROPERTY_SPEED_BONUS]: require('./speed-bonus')
}

