const { computeRuleValue } = require('../common/compute-rule-value')
const CONSTS = require("../../../consts");
const {getDisAndAdvEffectRegistry, getThoseProvidedByEffects} = require("../common/get-disandadv-effect-registry");

/**
 * Etabli la liste des avantages de THIS par rapport à sa cible THIS.target
 * @param state
 * @param getters {D20CreatureStoreGetters}
 * @return {D20AdvantagesOrDisadvantages}
 */
module.exports = (state, getters) => {
    // const myConditions = getters.getConditions
    // const myConditionSources = getters.getConditionSources
    const targetConditions = getters.getTargetConditions
    const targetConditionSources = getters.getTargetConditionSources
    // const aggressorConditions = getters.getAggressorConditions
    // const aggressorConditionSources = getters.getAggressorConditionSources
    const myID = getters.getId
    const oRelevantEffects = getters
        .getEffects
        .filter(effect => effect.type === CONSTS.EFFECT_ADVANTAGE)
    const oRelevantProperties = getters
        .getEquipmentExtraProperties
        .filter(prop => prop.property === CONSTS.EXTRA_PROPERTY_ADVANTAGE)
    const oAdvantageEffectRegistry = getDisAndAdvEffectRegistry(oRelevantEffects, oRelevantProperties)

    /**
     * Returns true if the condition is generated by this
     * @param sCondition
     * @returns {*}
     */
    const targetAffectedByMe = sCondition => targetConditions.has(sCondition) &&
        targetConditionSources[sCondition].has(myID)

    /*
    Commencer par définir les règles.
    Ces règles permettront au système d'afficher pour quelles raisons on bénéficie ou pas d'un avantage
     */

    // TARGET_CHARMED : La cible est charmée par this
    const TARGET_CHARMED = targetAffectedByMe(CONSTS.CONDITION_CHARMED)

    // TARGET_INCAPACITATED : La cible ne peut pas se défendre
    const TARGET_INCAPACITATED = targetConditions.has(CONSTS.CONDITION_INCAPACITATED)

    // UNDETECTED : La cible ne peut pas détecter this, mais this perçoit la cible
    const UNDETECTED = getters.getEntityVisibility.detectable.target &&
        !getters.getEntityVisibility.detectedBy.target

    /*
    Définir l'ossature D20AdvantagesOrDisadvantages
     */
    return {
        ROLL_TYPE_ATTACK: {
            ABILITY_STRENGTH: computeRuleValue({
                UNDETECTED,
                TARGET_INCAPACITATED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_ATTACK, CONSTS.ABILITY_STRENGTH)
            }),
            ABILITY_DEXTERITY: computeRuleValue({
                UNDETECTED,
                TARGET_INCAPACITATED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_ATTACK, CONSTS.ABILITY_DEXTERITY)
            }),
            ABILITY_CONSTITUTION: computeRuleValue({
                UNDETECTED,
                TARGET_INCAPACITATED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_ATTACK, CONSTS.ABILITY_CONSTITUTION)
            }),
            ABILITY_INTELLIGENCE: computeRuleValue({
                UNDETECTED,
                TARGET_INCAPACITATED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_ATTACK, CONSTS.ABILITY_INTELLIGENCE)
            }),
            ABILITY_WISDOM: computeRuleValue({
                UNDETECTED,
                TARGET_INCAPACITATED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_ATTACK, CONSTS.ABILITY_WISDOM)
            }),
            ABILITY_CHARISMA: computeRuleValue({
                UNDETECTED,
                TARGET_INCAPACITATED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_ATTACK, CONSTS.ABILITY_CHARISMA)
            })
        },
        ROLL_TYPE_SAVE: {
            ABILITY_STRENGTH: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_SAVE, CONSTS.ABILITY_STRENGTH)
            }),
            ABILITY_DEXTERITY: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_SAVE, CONSTS.ABILITY_DEXTERITY)
            }),
            ABILITY_CONSTITUTION: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_SAVE, CONSTS.ABILITY_CONSTITUTION)
            }),
            ABILITY_INTELLIGENCE: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_SAVE, CONSTS.ABILITY_INTELLIGENCE)
            }),
            ABILITY_WISDOM: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_SAVE, CONSTS.ABILITY_WISDOM)
            }),
            ABILITY_CHARISMA: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_SAVE, CONSTS.ABILITY_CHARISMA)
            })
        },
        ROLL_TYPE_CHECK: {
            ABILITY_STRENGTH: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, CONSTS.ABILITY_STRENGTH)
            }),
            ABILITY_DEXTERITY: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, CONSTS.ABILITY_DEXTERITY)
            }),
            ABILITY_CONSTITUTION: computeRuleValue({
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, CONSTS.ABILITY_CONSTITUTION)
            }),
            ABILITY_INTELLIGENCE: computeRuleValue({
                TARGET_CHARMED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, CONSTS.ABILITY_INTELLIGENCE)
            }),
            ABILITY_WISDOM: computeRuleValue({
                TARGET_CHARMED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, CONSTS.ABILITY_WISDOM)
            }),
            ABILITY_CHARISMA: computeRuleValue({
                TARGET_CHARMED,
                ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, CONSTS.ABILITY_CHARISMA)
            })
        }
    }
}
