const CONSTS = require("../../../../../consts");
const { computeRuleValue } = require('../../../../../store/creature/common/compute-rule-value')
const {getDisAndAdvEffectRegistry, getThoseProvidedByEffects} = require("../../../../../store/creature/common/get-disandadv-effect-registry");

/**
 * Etabli la liste des avantages de THIS par rapport à sa cible THIS.target
 * @param state
 * @param getters {D20CreatureStoreGetters}
 * @return {D20AdvantagesOrDisadvantages}
 */
module.exports = (state, getters) => {
    // const myConditions = getters.getConditions
    // const myConditionSources = getters.getConditionSources
    const targetConditions = getters.getTargetConditions
    const targetConditionSources = getters.getTargetConditionSources
    // const aggressorConditions = getters.getAggressorConditions
    // const aggressorConditionSources = getters.getAggressorConditionSources
    const myID = getters.getId
    const oRelevantEffects = getters
        .getEffects
        .filter(effect => effect.type === CONSTS.EFFECT_DISADVANTAGE)
    const oRelevantProperties = getters
        .getEquipmentItemProperties
        .filter(prop => prop.property === CONSTS.ITEM_PROPERTY_DISADVANTAGE)
    const oAdvantageEffectRegistry = getDisAndAdvEffectRegistry(oRelevantEffects, oRelevantProperties)

    /**
     * Returns true if the condition is generated by this
     * @param sCondition
     * @returns {*}
     */
    const targetAffectedByMe = sCondition => targetConditions.has(sCondition) &&
        targetConditionSources[sCondition].has(myID)

    // La créature porte une armure qui n'est pas adaptée au déplacement furtif
    const WEARING_NON_STEALTH_ARMOR = getters.isWearingStealthDisadvantagedArmor

    /*
    Commencer par définir les règles.
    Ces règles permettront au système d'afficher pour quelles raisons on bénéficie ou pas d'un avantage
     */

    /*
    Définir l'ossature D20AdvantagesOrDisadvantages
     */
    return {
        SKILL_ACROBATICS: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_ACROBATICS')
        }),
        SKILL_ANIMAL_HANDLING: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_ANIMAL_HANDLING')
        }),
        SKILL_ARCANA: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_ARCANA')
        }),
        SKILL_ATHLETICS: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_ATHLETICS')
        }),
        SKILL_DECEPTION: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_DECEPTION')
        }),
        SKILL_DISARM_TRAP: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_DISARM_TRAP')
        }),
        SKILL_HISTORY: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_HISTORY')
        }),
        SKILL_INSIGHT: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_INSIGHT')
        }),
        SKILL_INTIMIDATION: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_INTIMIDATION')
        }),
        SKILL_INVESTIGATION: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_INVESTIGATION')
        }),
        SKILL_MEDICINE: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_MEDICINE')
        }),
        SKILL_NATURE: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_NATURE')
        }),
        SKILL_PERFORMANCE: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_PERFORMANCE')
        }),
        SKILL_PERSUASION: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_PERSUASION')
        }),
        SKILL_RELIGION: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_RELIGION')
        }),
        SKILL_SLEIGHT_OF_HAND: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_SLEIGHT_OF_HAND')
        }),
        SKILL_STEALTH: computeRuleValue({
            WEARING_NON_STEALTH_ARMOR,
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_STEALTH')
        }),
        SKILL_SURVIVAL: computeRuleValue({
            ...getThoseProvidedByEffects(oAdvantageEffectRegistry, CONSTS.ROLL_TYPE_CHECK, 'SKILL_SURVIVAL')
        })
    }
}
