module.exports = {
    ENTITY_TYPE_ITEM: 'ENTITY_TYPE_ITEM',
    ENTITY_TYPE_CREATURE: 'ENTITY_TYPE_CREATURE',

    MATERIAL_WOOD: 'MATERIAL_WOOD',
    MATERIAL_STEEL: 'MATERIAL_STEEL',
    MATERIAL_ALUMINUM: 'MATERIAL_ALUMINUM',
    MATERIAL_SILVER: 'MATERIAL_ALUMINUM',

    ABILITY_STRENGTH: 'strength',
    ABILITY_DEXTERITY: 'dexterity',
    ABILITY_CONSTITUTION: 'constitution',
    ABILITY_INTELLIGENCE: 'intelligence',
    ABILITY_WISDOM: 'wisdom',
    ABILITY_CHARISMA: 'charisma',

    CLASS_TOURIST: 'tourist',

    EQUIPMENT_SLOT_HEAD: 'head', // helms, caps
    EQUIPMENT_SLOT_NECK: 'neck', // necklaces, amulets
    EQUIPMENT_SLOT_CHEST: 'chest', // armors
    EQUIPMENT_SLOT_ARMS: 'arms', // bracers, gauntlets
    EQUIPMENT_SLOT_BACK: 'back', // capes, backpacks
    EQUIPMENT_SLOT_WAIST: 'waist', // belts
    EQUIPMENT_SLOT_FEET: 'feet', // boots
    EQUIPMENT_SLOT_LEFTFINGER: 'leftFinger', // rings
    EQUIPMENT_SLOT_RIGHTFINGER: 'rightFinger', // rings
    EQUIPMENT_SLOT_MELEEWEAPON: 'meleeWeapon',
    EQUIPMENT_SLOT_RANGEDWEAPON: 'rangedWeapon',
    EQUIPMENT_SLOT_SHIELD: 'shield',
    EQUIPMENT_SLOT_AMMO: 'ammo',

    PROFICIENCY_ARMOR_LIGHT: "PROFICIENCY_ARMOR_LIGHT",
    PROFICIENCY_ARMOR_MEDIUM: "PROFICIENCY_ARMOR_MEDIUM",
    PROFICIENCY_ARMOR_HEAVY: "PROFICIENCY_ARMOR_HEAVY",
    PROFICIENCY_ARMOR_SHIELD: "PROFICIENCY_ARMOR_SHIELD",

    PROFICIENCY_WEAPON_SIMPLE: "PROFICIENCY_WEAPON_SIMPLE",
    PROFICIENCY_WEAPON_MARTIAL: "PROFICIENCY_WEAPON_MARTIAL",

    PROFICIENCY_SAVING_THROW_STRENGTH: "PROFICIENCY_SAVING_THROW_STRENGTH",
    PROFICIENCY_SAVING_THROW_DEXTERITY: "PROFICIENCY_SAVING_THROW_DEXTERITY",
    PROFICIENCY_SAVING_THROW_CONSTITUTION: "PROFICIENCY_SAVING_THROW_CONSTITUTION",
    PROFICIENCY_SAVING_THROW_INTELLIGENCE: "PROFICIENCY_SAVING_THROW_INTELLIGENCE",
    PROFICIENCY_SAVING_THROW_WISDOM: "PROFICIENCY_SAVING_THROW_WISDOM",
    PROFICIENCY_SAVING_THROW_CHARISMA: "PROFICIENCY_SAVING_THROW_CHARISMA"
}
