/* THIS FILE IS AUTO-GENERATED ! DO NOT MODIFY ! Date: 04/09/2023, 15:46:38 */
const CONSTS = require('../consts')
module.exports = {
  [CONSTS.EFFECT_ABILITY_BONUS]: require('./ability-bonus'),
  [CONSTS.EFFECT_AC_BASE]: require('./ac-base'),
  [CONSTS.EFFECT_AC_BONUS]: require('./ac-bonus'),
  [CONSTS.EFFECT_ADVANTAGE]: require('./advantage'),
  [CONSTS.EFFECT_ATTACK_BONUS]: require('./attack-bonus'),
  [CONSTS.EFFECT_CONDITION_IMMUNITY]: require('./condition-immunity'),
  [CONSTS.EFFECT_CONDITION]: require('./condition'),
  [CONSTS.EFFECT_CRITICAL_THREAT]: require('./critical-threat'),
  [CONSTS.EFFECT_DAMAGE_BONUS]: require('./damage-bonus'),
  [CONSTS.EFFECT_DAMAGE_IMMUNITY]: require('./damage-immunity'),
  [CONSTS.EFFECT_DAMAGE_REDUCTION]: require('./damage-reduction'),
  [CONSTS.EFFECT_DAMAGE_RESISTANCE]: require('./damage-resistance'),
  [CONSTS.EFFECT_DAMAGE_VULNERABILITY]: require('./damage-vulnerability'),
  [CONSTS.EFFECT_DAMAGE]: require('./damage'),
  [CONSTS.EFFECT_DISADVANTAGE]: require('./disadvantage'),
  [CONSTS.EFFECT_DUMMY]: require('./dummy'),
  [CONSTS.EFFECT_EXHAUSTION]: require('./exhaustion'),
  [CONSTS.EFFECT_EXTRA_ATTACKS]: require('./extra-attacks'),
  [CONSTS.EFFECT_GROUP]: require('./group'),
  [CONSTS.EFFECT_HEAL]: require('./heal'),
  [CONSTS.EFFECT_HP_BONUS]: require('./hp-bonus'),
  [CONSTS.EFFECT_INVISIBILITY]: require('./invisibility'),
  [CONSTS.EFFECT_MASSIVE_CRITICAL]: require('./massive-critical'),
  [CONSTS.EFFECT_MATERIAL_VULNERABILITY]: require('./material-vulnerability'),
  [CONSTS.EFFECT_MELEE_ATTACK_BONUS]: require('./melee-attack-bonus'),
  [CONSTS.EFFECT_MUMMY_ROT]: require('./mummy-rot'),
  [CONSTS.EFFECT_PHARMA]: require('./pharma'),
  [CONSTS.EFFECT_POISON]: require('./poison'),
  [CONSTS.EFFECT_RANGED_ATTACK_BONUS]: require('./ranged-attack-bonus'),
  [CONSTS.EFFECT_REROLL]: require('./reroll'),
  [CONSTS.EFFECT_SAVING_THROW_BONUS]: require('./saving-throw-bonus'),
  [CONSTS.EFFECT_SKILL_EXPERTISE]: require('./skill-expertise'),
  [CONSTS.EFFECT_SPEED_BONUS]: require('./speed-bonus'),
  [CONSTS.EFFECT_TRUE_SIGHT]: require('./true-sight')
}

